version: '3.8'

services:
  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    ports:
      - "9000:9000"
    environment:
      - ASR_MODEL=base

  llm:
    build:
     context: ./app
     dockerfile: Dockerfile.llm
    ports:
    - "11434:11434"
    volumes:
    - ollama_data:/root/.ollama
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434" ]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build: ./app
    image: voice-api:latest
    ports:
      - "8000:8000"
    depends_on:
      - whisper
      - llm
  tts:
    image: synesthesiam/mozillatts:latest
    ports:
      - "5002:5002"
    environment:
      - TTS_MODEL=tts_models/en/ljspeech/tacotron2-DDC
    depends_on:
      - api

volumes:
  ollama_data:
